SRC_URI_append_cl-som-imx6 = " \
	file://0000-cl-som-imx6-Add-defconfig.patch \
	file://0001-cl-som-imx6-Add-dts.patch \
	file://0002-cl-som-imx6-Add-machine-driver.patch \
	file://0003-cl-som-imx6-defconfig-Update-CONFIG_LOCALVERSION.patch \
	file://0004-cl-som-imx6-Update-device-tree-files.patch \
	file://0005-cl-som-imx6-Update-defconfig.patch \
	file://0007-gpu-viv-Fix-build-issue-for-beinf-buid-as-a-module.patch \
	file://0008-cl-som-imx6-dts-Remove-imx6qdl-sb-fx6x.dtsi.patch \
	file://0009-cl-som-imx8-dts-Fix-cma-location.patch \
	file://0010-cl-som-imx6-Update-defconfig.patch \
	file://defconfig \
"
