SRC_URI_append_cl-som-imx6 = " \
	file://0000-cl-som-imx6-Add-defconfig.patch \
	file://0001-cl-som-imx6-Add-dts.patch \
	file://0002-cl-som-imx6-Add-machine-driver.patch \
	file://0003-cl-som-imx6-defconfig-Update-CONFIG_LOCALVERSION.patch \
	file://0004-cl-som-imx6-Update-device-tree-files.patch \
	file://0005-cl-som-imx6-Update-defconfig.patch \
	file://0006-cl-som-imx6-dts-Update-the-spi-flash-name.patch \
	file://0007-gpu-viv-Fix-build-issue-for-beinf-buid-as-a-module.patch \
	file://0008-cl-som-imx6-dts-Remove-imx6qdl-sb-fx6x.dtsi.patch \
	file://0009-cl-som-imx8-dts-Fix-cma-location.patch \
	file://0010-cl-som-imx6-Update-defconfig.patch \
	file://0011-cl-som-imx6-dts-Fix-cma-range.patch \
	file://0012-cl-som-imx6-dts-Enable-wifi-as-brcm-bcm4329-fmac.patch \
	file://0013-cl-som-imx6-config-Disable-CONFIG_FW_LOADER_USER_HEL.patch \
	file://0014-cl-som-imx6-dts-Enable-bluetooth.patch \
	file://0015-hci_bcm-Fix-power-on-issue.patch \
	file://0016-cl-som-imx6-config-Enable-bluetooth.patch \
	file://0017-cl-som-imx6-config-Fix-LOCALVERSION.patch \
	file://defconfig \
"
