SRC_URI_append = " \
	file://0000-cl-som-imx6-dts-Add-the-SoM-dts.patch \
	file://0001-cl-som-imx6-mach-Add-the-SoM-mach-driver.patch \
	file://0002-cl-som-imx6-conf-Add-the-SoM-config.patch \
	file://0003-hci_bcm-Refactoring-the-bcm_setup.patch \
	file://0004-cl-som-imx6-dts-Remove-an-incorrect-clk-node.patch \
	file://0005-btwilink-add-minimal-device-tree-support.patch \
	file://0006-Bluetooth-Add-tty-HCI-driver.patch \
	file://0007-sil164-add-dvi-transmitter-simple-driver.patch \
	file://0008-ARM-i.MX6UL-audio-0-add-analog-audio-support-switch.patch \
	file://0009-ARM-i.MX6UL-Add-cl-som-imx6ul-platform-driver.patch \
	file://0010-cl-som-imx6ul-Add-device-tree-files.patch \
	file://0011-cl-som-imx6ul-Add-defconfig.patch \
	file://defconfig \
"
