SRC_URI_append_cl-som-imx6 = " \
	file://0000-Makefile-Add-u-boot.imx-targer.patch \
	file://0001-compulab-epprom-Add-CONFIG_DM_I2C-support.patch \
	file://0002-compulab-cl-som-imx6-Add-board-support.patch \
	file://0003-compulab-cl-som-imx6-spl-Enable-CONFIG_MX6_DDRCAL.patch \
	file://0004-compulab-cl-som-imx6-Update-board-functions-names.patch \
	file://0005-compulab-cl-som-imx6-Add-spl_mx6qp_noc_init.patch \
	file://0006-cl-som-imx6-u-boot-Enable-CONFIG_COMPULAB_BANK_LAYOU.patch \
	file://0007-cl-som-imx6-defconfig-Enable-CONFIG_CMD_MEMTEST.patch \
"
