SRC_URI_append_cl-som-imx6ul += "file://cl_som_imx6ul_defconfig \
	file://cl_som_imx6ul_nospl_defconfig \
	file://0001-arm-imx6ul-add-support-for-Compulab-cl-som-imx6ul.patch \
	file://0002-arm-imx6ul-add-extraversion-for-cl-som-imx6ul.patch \
	file://0004-arm-imx6ul-enable-USB-Networking.patch \
	file://0005-arm-imx6ul-enable-nand-for-cl-som-imx6ul.patch \
	file://0006-arm-imx6ul-add-memory-size-detection-for-cl-som-imx6.patch \
	file://0007-arm-imx6ul-tag-U-Boot-version-cl-som-imx6ul-1.0.patch \
	file://0008-arm-imx6ul-fec-Fix-fec-phy-settings.patch \
	file://0009-arm-imx6ul-tag-U-Boot-version-cl-som-imx6ul-1.1.patch \
	file://0010-arm-imx6ul-Enable-CONFIG_OF_BOARD_SETUP.patch \
	file://0011-arm-imx6ul-Enable-debug-uart-in-SPL.patch \
	file://0012-arm-imx6ul-Make-SPL-read-a-raw-U-Boot.patch \
"
